---
- name: Set hostname
  vyos_config:
    lines:
      - set system host-name "{{ inventory_hostname }}"
  tags:
    - hostname

- name: Get current router variables
  set_fact:
    current_router_vars: "{{ router_vars | selectattr('hostname', 'equalto', inventory_hostname) | list | first | default([]) + [item] }}"
  tags:
    - interfaces
    - ha

- name: Configure interfaces
  vyos_config:
    lines:
      - set interfaces ethernet "{{ item.name }} address {{ item.ip }}/{{ item.subnet_mask }}"
      - set interfaces ethernet "{{ item.name }} description {{ item.description }}"
  with_items: "{{ current_router_vars[0].interfaces }}"
  tags:
    - interfaces

- name: Configure HA
  vyos_config:
    lines:
      - set high-availability vrrp group "{{ ha_group_name }}" vrid "{{ vrid }}"
      - set high-availability vrrp group "{{ ha_group_name }}" interface "{{ ha_interfaces }}"
      - set high-availability vrrp group "{{ ha_group_name }}" virtual-address "{{ ha_vip }}"
      - set high-availability vrrp group "{{ ha_group_name }}" priority "{{ current_router_vars[0].ha.priority }}"
      - set high-availability vrrp group "{{ ha_group_name }}" hello-source-address "{{ ha_source_address }}"
      - set high-availability vrrp group "{{ ha_group_name }}" peer-address "{{ ha_peer_address }}"
      - set high-availability vrrp group "{{ ha_group_name }}" advertise-interval '1'
      - set high-availability vrrp group "{{ ha_group_name }}" preempt-delay '30'
  tags:
    - ha

- name: Check if VIP is reachable
  command: ping -c 1 -W 10 "{{ ha_vip }}"
  register: ping_result
  changed_when: false
  failed_when: ping_result.rc != 0
  tags:
    - ha